apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: hiring-agent
type: Opaque
data:
  openai-api-key: b3BlbmFpLWtleS1nb2VzLWhlcmU=
  aws-access-key: YXdzLWFjY2Vzcy1rZXktZ29lcy1oZXJl
  aws-secret-key: YXdzLXNlY3JldC1rZXktZ29lcy1oZXJl
  db-password: ZGItcGFzc3dvcmQtZ29lcy1oZXJl