apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: hiring-agent
type: Opaque
stringData:  # Using stringData instead of data for direct string values
  openai-api-key: "your-openai-api-key"
  aws-access-key: "your-aws-access-key"
  aws-secret-key: "your-aws-secret-key"