apiVersion: v1
kind: Service
metadata:
  name: hiring-agent-service
  namespace: hiring-agent
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: hiring-agent
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: hiring-agent
data:
  s3-bucket-name: "hiring-agent-resumes"
  allowed-origins: "*"
  log-level: "INFO"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: hiring-agent
type: Opaque
data:
  # Replace these with your actual base64 encoded values
  openai-api-key: <base64-encoded-api-key>
---
apiVersion: v1
kind: Namespace
metadata:
  name: hiring-agent
