apiVersion: apps/v1
kind: Deployment
metadata:
  name: hiring-agent
  namespace: hiring-agent
  labels:
    app: hiring-agent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hiring-agent
  template:
    metadata:
      labels:
        app: hiring-agent
    spec:
      containers:
      - name: hiring-agent
        image: hiring-agent:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: openai-api-key
        - name: S3_BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: s3-bucket-name
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 3
          periodSeconds: 5
        volumeMounts:
        - name: temp-storage
          mountPath: /tmp
      volumes:
      - name: temp-storage
        emptyDir: {}